spring.application.name=MathruAI_BackEnd

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/MathruAi_Database?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=20000624
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=U2VjdXJlSldUS2V5MTIzITIzITIzIUxvbmdFbm91hfshfjshfZ2gadsd
jwt.expiration=604800000

#cors
#spring.web.cors.allowed-origins=http://localhost:3000,http://localhost:5000
#spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
#spring.web.cors.allowed-headers=*
#spring.web.cors.allow-credentials=true


# SpringDoc swagger Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.operationsSorter=method

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hirusdn2000@gmail.com
spring.mail.password=kful rvaj xpxl ugxh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=hirusdn2000@gmail.com
app.mail.enabled=true
